#lang typed/racket/base

(provide (all-defined-out))
(provide (rename-out [geo-polyline geo-lines]))
(provide (rename-out [geo-sandglass geo-hourglass]))
(provide (rename-out [geo-arrowhead geo-dart]))

(provide geo-blank geo-ghost geo:blank? Geo:Blank)
(provide geo-bitmap geo:bitmap? Geo:Bitmap)
(provide geo-rectangular geo:λbitmap? Geo:λBitmap)
(provide geo-text geo:text? Geo:Text)
(provide geo-toy-text geo:toy-text? Geo:Toy-Text)
(provide geo-paragraph geo:para? Geo:Paragraph)
(provide geo-square geo-rectangle geo:rect? Geo:Rectangle)
(provide geo-vline geo-hline geo:line? Geo:Line)
(provide geo-circle geo:circle? Geo:Circle)
(provide geo-ellipse geo:ellipse? Geo:Ellipse)
(provide geo-arc geo:arc? Geo:Arc)
(provide geo-sector geo:sector? Geo:Sector)
(provide geo-regular-polygon geo:regular-polygon? Geo:Regular-Polygon)
(provide geo-polygon geo:polygon? Geo:Polygon)
(provide geo-polyline geo:polyline? Geo:Polyline)
(provide geo-stadium geo:stadium? Geo:Stadium)
(provide geo-sandglass geo:sandglass? Geo:Sandglass)
(provide geo-arrow geo-arrowhead geo:arrow? Geo:Arrow)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(require "digitama/dc/text.rkt")
(require "digitama/dc/rect.rkt")
(require "digitama/dc/circle.rkt")
(require "digitama/dc/plain.rkt")
(require "digitama/dc/raster.rkt")
(require "digitama/dc/line.rkt")
(require "digitama/dc/polygon.rkt")
(require "digitama/dc/arrow.rkt")

(require "digitama/dc/more.rkt")
