((tamer-handbook . "Tamer's Handbook")
 (handbook-rule . "Rule")
 (handbook-story . "Story")
 (handbook-scenario . "Scenario")
 (handbook-appendix . "Appendix")
 (handbook-auxiliary . "~a Auxiliaries")
 (handbook-appendix-disclaim . "In order to avoid polluting your eyes, any less important things are moved here. (also see ~a)") #| ~a: links to tamer.rkt |#)