((tamer-handbook . "驯兽师手册")
 (handbook-story . "故事")
 (handbook-scenario . "场景")
 (handbook-reference . "参考文献")
 (handbook-appendix . "附录")
 (handbook-bibliography . "参考条目")
 (handbook-digimon . "相关项目")
 (handbook-index . "索引"))
